lua/gen/init.lua
This will ensure that the select menu options have the same ordering every time the menu appears, since currently they are defined in a hash table and Lua provides no consistent ordering of items iterated via `pairs`. The default vim select menu utilizes numeric selection of options, so having consistent ordering is beneficial
=> Sort prompt keys for the prompt select menu

README.md, lua/gen/init.lua
This will allow you to reference the value in the unnamed (yank) register in your prompts. I made it throw an error if that value is empty, not sure if this kind of error reported is desired in the project. Feel free to change the name of the variable as well.
The idea here is that you have three sources of input:
* The register with data to reference
* The visual selection with text to modify
* The prompt for instructions to perform
Here's an example of how it might be used with a custom prompt I made:
https://github.com/David-Kunz/gen.nvim/assets/15198/394448c5-a248-469c-91bc-2908005fd617
```lua
Modify_With_Reference = {
prompt = table.concat({
"Referencing the following:",
"$register",
"Modify the following text, $input, just output the final text without additional quotes around it:", …
```
=> Add $register variable for prompts

lua/gen/init.lua
This adds a complete function to the `:Gen` user command with all the prompt names that match what's been typed (or listing everything if tab is pressed and nothing is typed.
=> add complete function for :Gen command

README.md, lua/gen/init.lua
This will allow you to provide a function when declaring the prompt for the `prompt` field. The function should return a string that will be used in the final prompt. The function is called every time a generate call is issued. Variables still work on the output string.
I gave the function one argument, a table of properties that are in scope relevant the interpolation of the prompt, should you want to do manual interpolation.
The purpose is to enable dynamic prompt generation that is more flexible than just the variable system. A few examples: 
* insert additional `vim.ui.input` calls to ask for more information about how to fill out the prompt
* automatically insert context on the prompt depending on the current file or directory.
* implement custom `$variables` in a prompt template …
=> Support defining a prompt as a function in addition to a string

lua/gen/init.lua
Previously, closing the vim.ui.select window, e.g. with `<esc>` would cause this error:
```
Error executing vim.schedule lua callback: vim/shared.lua:0: after the second argument: expected table, got nil                                                                                                                                                 
stack traceback:                                                                                                                                                                                                                                                
[C]: in function 'error' …
```
=> fix: handle cancellation of vim.ui.select by user

lua/gen/init.lua
When the preview window was closed with `q`, `on_stdout` would call `nvim_win_call` with an invalid window ID leading to errors.
This change cancels the job if an invalid window ID was detected in `on_stdout`.
=> fix: cancel job when floating window was closed prematurely

README.md, lua/gen/init.lua
This plugin looks awesome, but unfortunately, due to tech stack at my job, I'm forced to use Windows for development, so I have to run ollama in Docker container.
I've decided to add Docker container support for users as one of default supported ways to use plugin. To achive that i allowed users to specify `container` option. It accepts name of docker container as string and if provided changes few plugin behaviours:
- plugin will use `docker start` instead of `ollama serve` to ensure that ollama service is available
- plugin will use `docker exec $container ollama run $model $prompt` as default execution command
During process i was struggling with command returning error output to stderr, that i couldn't see, so I also implemented additional boolean option debugCommand that if set to …
=> feat: support for Docker container; printing command stderr to output window

README.md, lua/gen/init.lua
I changed the default model in `init.lua` and `README.md` from `mistral:instruct` to `mistral`
as `mistral:instruct` did not work and is also not in the [docs](https://ollama.ai/library/mistral)
(and fixed a missing comma in a code block in README.md).
=> From mistral:instruct to mistral

lua/gen/init.lua
Add linebreak option to wrap lines at whitespaces instead of in the middle of words.
=> Add linebreak option to wrap lines at whitespaces

lua/gen/prompts.lua
"output" was misspelled as "ouput" twice.
=> Fix typo in prompts.lua

lua/gen/init.lua
This change fixes #4 for double quotes on windows.
On windows `vim.fn.shellescape()` by default assumes the resulting command is gonna be called with cmd, so it substitutes double quotes with a pair of double quotes (" -> ""), and `vim.fn.jobstart()` uses `vim.o.shell` to run commands which by default is `'cmd.exe'`.
The problem comes from `vim.fn.json_encode()` that already tries to espace double quotes as `\"` so after `vim.fn.shellescape()` there would be a `\""` for every `"` in the command body. 
This fix basically substitutes `\""` for `\\\"` so that the final command is valid and contains any double quotes in the prompt correctly escaped.
---
**Original code:** 
```lua
vim.opt.signcolumn = "yes"
```
**Windows before fix:**
```bash
curl --silent --no-buffer -X POST …
```
=> substitute \"" with \\\" for cmd

README.md, lua/gen/init.lua
Hi there,
First of all, thanks for the great plugin! I love its simplicity and functionality. I find it useful sometimes to run the ollama server on a different computer than the computer I'm developing locally on. With that in mind, I wonder if you'd be open to this PR that adds `host` and `port` to options, and updates the `command` and `list_models` functions to use the specified host and port. This makes it easier to select a different host/port without needing to replace `command` and `list_models` with custom functions.
This is my first time working on a neovim plugin, and I'm very open to feedback in terms of any changes that might be needed!
Thanks!
=> feat: specify Ollama host and port in opts

lua/gen/init.lua
This PR adds the ability to set a prompt function that returns an empty string or a nil value, with the intent to have `gen.nvim` skip this action.  It is expected that the prompt function will inform the user that the action was terminated.
For example the following custom prompt will only work if called with a selection, where `gen.nvim` will pass it the visual selection.  If the selection is empty, the prompt will print "content is empty!" and return `nil`.
```lua
local gen = require'gen'
gen.prompts['Testcases_for_code'] = {
prompt = function(opt)
if opt.content == "" then
print("content is empty!")
return nil
end
if opt.filetype == 'cpp' or opt.filetype == 'c' then
return "Using C++20 and googletest generate testcases for the following code:"
.. opt.content .. "\n"
else
return "Using …
```
=> allow prompt function to cancel generate operation

lua/gen/init.lua
This PR adds support for the `chat` endpoint over the `generate` endpoint in Ollama. This in theory should also allow for use with OpenAI or an OpenAI API compatible backend.
My main motivation is to eventually be able to use gen.nvim with GPT4.
Tests:
Thanks!
Yomi
=> Add support for `chat` endpoint - OpenAI compatibility

lua/gen/init.lua
Hi David,
I'm still really enjoying working with your plugin!
I've noticed that on nightly versions of neovim (0.10-dev), there have been changes made to the nvim_buf_set_text() api. I believe the relevant PR that brought the changes in is [this one](https://github.com/neovim/neovim/pull/24901). As a result, when using gen.nvim in split mode, the buffer no longer scrolls as expected when ollama generates text that scrolls past the end of the viewable area. This PR adds support for proper buffer scrolling in nightly neovim versions (0.10-dev) while maintaining the functionality in the current stable versions of neovim. I believe that these changes to nvim_buf_set_text() will be in the next stable release of neovim.
Hopefully this will be useful, and if there are any changes you'd like me …
=> feat: support changes to nvim_buf_set_text()

lua/gen/init.lua
{end_col} is exclusive by nvim_buf_get_text and nvim_buf_set_text document
=> fix: get buf text in v-mode

lua/gen/init.lua
Hi David,
I recently noticed a small issue when `opts.show_prompt` is set to true. An earlier commit (ed802f06a691895c8d6c5cf88b70b698a52514ad) introduced the `run_command` function. As a result of this function, the local variable `prompt` does not exist in the scope of the `run_command` function. Instead, when `opts.show_prompt` is true, we now parse the `opts.prompt` variable, which is available in the `run_command` function.
I believe this PR fixes the issue. Hopefully it's useful!
Thanks,
John
=> fix: parse opts.prompt instead of prompt

lua/gen/init.lua
#107 Allow to refer to named register with `$register_<name>`, for example:
- `$register_a` refer to content in named register `a`
- `$register_0` refer to content just yarned
- `$register_*` refer to content in system clipboard
This would help creating resilient AI assistant key maps without interrupting the main work flow or force overwriting the default register, for example
```
require('gen').prompts['ExplainTerm'] = {
prompt = "Please translate \"$register_a\" into $register_l and explain its meaning in the follow text. Write your answer in $register_l:\n\n$register_b",
}
-- Explain the word under cursor or selection within the the context of the current sentence in a specific language
-- Language name should be stored in register L prior to performing the action, e.g. `let …
```
=> #107 feat: allow to refer named register with $register_<name>

lua/gen/init.lua
Hi there!
On my use-case I need to specify what kind of `display_mode` I want on the `prompt`, instead of using a global from the `setup`. 
This MR makes the usage of a property of the same name (`display_mode`) from the prompt, and fallback on the default from the config in case of its missing property.
If you need me to change something else let me know,
Thanks in advance and thanks for the nice plugin! :D
=> Add display mode for the prompt configuration

lua/gen/init.lua
Currently, floating window doesn't wrap text correctly. Upon looking into the source code it looks like some options are only being set for splits not floats. 
This PR should make the behavior more consistent. I think this will fix https://github.com/David-Kunz/gen.nvim/issues/53.
=> fix: correct floating window wrap behavior

README.md, lua/gen/init.lua
The default `markdown` filetype is great because it gives us syntax highlights etc. In my case though it also activates LSPs, some of which can be quite heavy (e.g., `ltex`) and were leading to full freezes. This options allows setting a new filetype for the result, giving more flexibility to users while having a sane default.
I personally use `markdown.gen` which gives me syntax highlights but does not trigger the LSPs.
=> feat: Allow configuration of result filetype

lua/gen/init.lua
I have a [`curlrc` file](https://github.com/aldur/dotfiles/blob/master/various/curlrc) that enables more verbose logging.
`require('gen').select_model()` was failing because it tried parsing the additional output as well. 
This PR fixes the issue by ignoring the `rc`. I am not sure if it is the best approach, as someone might rely on the rc file e.g. to set proxies? If that's the case, we could make `curl` options an additional configuration parameter.
Here's the error log, just in case.
```log
|| E5108: Error executing lua Vim:E474: Unidentified byte: * Host localhost:11434 was resolved.
|| * IPv6: ::1
|| * IPv4: 127.0.0.1
|| *   Trying 127.0.0.1:11434...
|| * Connected to localhost (127.0.0.1) port 11434
|| > GET /api/tags HTTP/1.1
|| > Host: localhost:11434
|| > User-Agent: Mozilla/5.0 …
```
=> fix: Disable curlrc

README.md
I changed the domain of Ollama's link from ".ai" to ".com" because it wasn't loading.
=> fix: typo in a link

lua/gen/init.lua
Add extract parameter to be specified as a function instead of just a string, to allow custom behavior to be implemented.
Rationale: the new deepseek-r1 show promising results with ollama, but it includes it's thinking context in the format `<think>context</think>answer`, and I'm only interested in extracting the `answer` bit into my working text buffer, and I wanted a generic `extract`, and I wanted it to work whether the `<think>` tags are available or not, and that wouldn't be possible with the standard string extract function. Therefore, I added support for a function.
With this, I add the following to my global opts:
```
extract = function (opts)
local result = opts.result_string:match("^<think>.-</think>(.*)$")
if result then
return result
else
return opts.result_string
end
end,
``` …
=> Support extract option as a function
